using Bunit;
using Microsoft.Extensions.DependencyInjection;
using MudBlazor.Services;
using NSubstitute;
using ScrumPilot.Shared.Models;
using ScrumPilot.Web.Pages;
using ScrumPilot.Web.Services;
using Xunit;

namespace ScrumPilot.UnitTests.Frontend.PageTests
{
    public class DraftPbiPageTests : FrontendTestBase
    {
        public DraftPbiPageTests()
        {
            // Base class handles MudServices and basic JSInterop setup
        }

        [Fact]
        public void DraftPbiPage_RendersCorrectPageStructure()
        {
            // Act
            var component = Render<DraftPbiPage>();

            // Assert - Focus on page structure and content, not complex interactions
            Assert.Contains("AI-Generated PBIs", component.Markup);
            Assert.Contains("Review and commit PBIs generated by AI", component.Markup);
            Assert.Contains("mud-container", component.Markup);
            Assert.Contains("mud-paper", component.Markup);
        }

        [Fact]
        public void DraftPbiPage_ShowsLoadingState_Initially()
        {
            // Act
            var component = Render<DraftPbiPage>();

            // Assert - Just verify the component renders (loading logic happens async)
            Assert.NotNull(component.Markup);
            Assert.Contains("mud-container", component.Markup);
            // Note: Loading state might not show due to async timing in tests
        }

        [Fact]
        public void DraftPbiPage_RendersWithoutExceptions()
        {
            // Act & Assert - Basic smoke test
            var component = Render<DraftPbiPage>();
            Assert.NotNull(component);
            Assert.NotNull(component.Markup);
        }

        [Fact]
        public void DraftPbiPage_UsesCorrectLayoutStructure()
        {
            // Act  
            var component = Render<DraftPbiPage>();

            // Assert - Test that the page follows the expected layout structure
            Assert.Contains("pa-4", component.Markup); // Padding class
            Assert.Contains("pa-6", component.Markup); // Paper padding
            Assert.Contains("mb-6", component.Markup); // Margin bottom
        }

        [Fact]
        public void DraftPbiPage_RequestsSelectedProject_AndReloadsWhenSelectionChanges()
        {
            var projectState = Services.GetRequiredService<ProjectStateService>();
            projectState.SetProject(new Project { ProjectId = 7, ProjectName = "Seven" });

            var component = Render<DraftPbiPage>();

            component.WaitForAssertion(() =>
                Assert.Contains("api/Pbi/getDraftPbis?projectId=7", HttpRequests));

            projectState.SetProject(new Project { ProjectId = 9, ProjectName = "Nine" });

            component.WaitForAssertion(() =>
                Assert.Contains("api/Pbi/getDraftPbis?projectId=9", HttpRequests));
            Assert.Equal(2, HttpRequests.Count);
        }

        [Fact]
        public void DraftPbiPage_ShowsSelectProjectStateWithoutRequest()
        {
            var component = Render<DraftPbiPage>();

            Assert.Contains("Select a project to view its draft PBIs.", component.Markup);
            Assert.Empty(HttpRequests);
        }
    }
}
