using Bunit;
using Microsoft.Extensions.DependencyInjection;
using MudBlazor.Services;
using NSubstitute;
using ScrumPilot.Shared.Models;
using ScrumPilot.Web.Pages;
using System.Net.Http.Json;
using Xunit;

namespace ScrumPilot.UnitTests.Frontend.PageTests
{
    public class DraftStoriesPageTests : FrontendTestBase
    {
        public DraftStoriesPageTests()
        {
            // Base class handles MudServices and basic JSInterop setup
        }

        [Fact]
        public void DraftStoriesPage_RendersCorrectPageStructure()
        {
            // Act
            var component = Render<DraftStoriesPage>();

            // Assert - Focus on page structure and content, not complex interactions
            Assert.Contains("AI-Generated User Stories", component.Markup);
            Assert.Contains("Review and commit user stories generated by AI", component.Markup);
            Assert.Contains("mud-container", component.Markup);
            Assert.Contains("mud-paper", component.Markup);
        }

        [Fact]
        public void DraftStoriesPage_ShowsLoadingState_Initially()
        {
            // Act
            var component = Render<DraftStoriesPage>();

            // Assert - Just verify the component renders (loading logic happens async)
            Assert.NotNull(component.Markup);
            Assert.Contains("mud-container", component.Markup);
            // Note: Loading state might not show due to async timing in tests
        }

        [Fact]
        public void DraftStoriesPage_RendersWithoutExceptions()
        {
            // Act & Assert - Basic smoke test
            var component = Render<DraftStoriesPage>();
            Assert.NotNull(component);
            Assert.NotNull(component.Markup);
        }

        [Fact]
        public void DraftStoriesPage_UsesCorrectLayoutStructure()
        {
            // Act  
            var component = Render<DraftStoriesPage>();

            // Assert - Test that the page follows the expected layout structure
            Assert.Contains("pa-4", component.Markup); // Padding class
            Assert.Contains("pa-6", component.Markup); // Paper padding
            Assert.Contains("mb-6", component.Markup); // Margin bottom
        }
    }
}
