// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrumPilot.Data.Context;

#nullable disable

namespace ScrumPilot.Data.Migrations
{
    [DbContext(typeof(ScrumPilotContext))]
    [Migration("20260402202256_AddTranscripts")]
    partial class AddTranscripts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ScrumPilot.Shared.Models.AudioTranscript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AudioTranscripts");
                });

            modelBuilder.Entity("ScrumPilot.Shared.Models.MessageTranscript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MessageTranscripts");
                });

            modelBuilder.Entity("ScrumPilot.Shared.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("ScrumPilot.Shared.Models.MessageTranscript", b =>
                {
                    b.OwnsMany("ScrumPilot.Shared.Models.DiscordMessage", "Messages", b1 =>
                        {
                            b1.Property<int>("MessageTranscriptId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.HasKey("MessageTranscriptId", "__synthesizedOrdinal");

                            b1.ToTable("MessageTranscripts");

                            b1.ToJson("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageTranscriptId");

                            b1.OwnsOne("ScrumPilot.Shared.Models.DiscordAuthor", "Author", b2 =>
                                {
                                    b2.Property<int>("DiscordMessageMessageTranscriptId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("DiscordMessage__synthesizedOrdinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Username")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("DiscordMessageMessageTranscriptId", "DiscordMessage__synthesizedOrdinal");

                                    b2.ToTable("MessageTranscripts");

                                    b2.WithOwner()
                                        .HasForeignKey("DiscordMessageMessageTranscriptId", "DiscordMessage__synthesizedOrdinal");
                                });

                            b1.Navigation("Author")
                                .IsRequired();
                        });

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
