using Microsoft.EntityFrameworkCore;
using ScrumPilot.Data.Context;
using ScrumPilot.Shared.Models;

namespace ScrumPilot.Data.Repositories
{
    public class PbiRepository : IPbiRepository
    {
        private readonly ScrumPilotContext _context;

        public PbiRepository(ScrumPilotContext context)
        {
            _context = context;
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetByProjectAsync(
            int projectId,
            bool? isDraft = null,
            CancellationToken cancellationToken = default)
        {
            var query = _context.Stories.Where(story => story.ProjectId == projectId);
            if (isDraft.HasValue)
                query = query.Where(story => story.IsDraft == isDraft.Value);
            return await query
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync(cancellationToken);
        }

        //public async Task<IEnumerable<Story>> GetActiveStoriesAsync(epicId) //This is for the Discord bot - Future State
        //{
        //    return await _context.Stories
        //        .Where(s => s.EpicId == epicId && s.Status != StoryStatus.Closed)
        //        .OrderByDescending(s => s.DateCreated)
        //        .ToListAsync();
        //}

        public async Task<ProductBacklogItem?> GetByIdAsync(int id, CancellationToken cancellationToken = default)
        {
            return await _context.Stories
                .FirstOrDefaultAsync(s => s.PbiId == id, cancellationToken);
        }

        public async Task<ProductBacklogItem> AddAsync(ProductBacklogItem story, CancellationToken cancellationToken = default)
        {
            // Note: Id will be auto-generated by the database (identity column)
            _context.Stories.Add(story);
            await _context.SaveChangesAsync(cancellationToken);
            return story;
        }

        public async Task<List<ProductBacklogItem>> AddRangeAsync(
            IEnumerable<ProductBacklogItem> stories,
            CancellationToken cancellationToken = default)
        {
            var items = stories.ToList();
            _context.Stories.AddRange(items);
            await _context.SaveChangesAsync(cancellationToken);
            return items;
        }

        public async Task<ProductBacklogItem> UpdateAsync(ProductBacklogItem story, CancellationToken cancellationToken = default)
        {
            await _context.SaveChangesAsync(cancellationToken);
            return story;
        }

        public async Task<bool> DeleteAsync(int id, CancellationToken cancellationToken = default)
        {
            var story = await _context.Stories.FindAsync([id], cancellationToken);
            if (story == null)
            {
                return false;
            }

            _context.Stories.Remove(story);
            await _context.SaveChangesAsync(cancellationToken);
            return true;
        }

        public async Task<IEnumerable<ProductBacklogItem>> GetFilteredPbisAsync(int? sprintId, int? epicId, int? projectId = null, CancellationToken cancellationToken = default)
        {
            var query = _context.Stories.Where(s => !s.IsDraft);

            if (projectId.HasValue)
                query = query.Where(s => s.ProjectId == projectId.Value);

            if (sprintId.HasValue)
            {
                if (sprintId.Value == -1)
                    query = query.Where(s => s.SprintId == null);
                else
                    query = query.Where(s => s.SprintId == sprintId.Value);
            }

            if (epicId.HasValue)
                query = query.Where(s => s.EpicId == epicId.Value);

            return await query
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync(cancellationToken);
        }
    }
}