using Microsoft.EntityFrameworkCore;
using ScrumPilot.Data.Context;
using ScrumPilot.Shared.Models;

namespace ScrumPilot.Data.Repositories
{
    public class StoryRepository : IStoryRepository
    {
        private readonly ScrumPilotContext _context;

        public StoryRepository(ScrumPilotContext context)
        {
            _context = context;
        }

        public async Task<IEnumerable<Story>> GetAllStoriesAsync()
        {
            return await _context.Stories
                .Where(s => !s.IsDraft)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        public async Task<Story?> GetByIdAsync(int id)
        {
            return await _context.Stories
                .FirstOrDefaultAsync(s => s.Id == id);
        }

        public async Task<Story> AddAsync(Story story)
        {
            // Note: Id will be auto-generated by the database (identity column)
            _context.Stories.Add(story);
            await _context.SaveChangesAsync();
            return story;
        }

        public async Task<Story> UpdateAsync(Story story)
        {
            _context.Entry(story).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return story;
        }

        public async Task<bool> DeleteAsync(int id) //This is a full delete right now. We may want to consider a soft delete. To Be Determined - TB
        {
            var story = await _context.Stories.FindAsync(id);
            if (story == null)
            {
                return false;
            }

            _context.Stories.Remove(story);
            await _context.SaveChangesAsync();
            return true;
        }

        public async Task<IEnumerable<Story>> GetByStatusAsync(StoryStatus status)
        {
            return await _context.Stories
                .Where(s => s.Status == status)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        public async Task<IEnumerable<Story>> GetDraftStoriesAsync()
        {
            return await _context.Stories
                .Where(s => s.IsDraft)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }

        public async Task<IEnumerable<Story>> GetNonDraftStoriesAsync()
        {
            return await _context.Stories
                .Where(s => !s.IsDraft)
                .OrderByDescending(s => s.DateCreated)
                .ToListAsync();
        }
    }
}