using System;

namespace ScrumPilot.Shared.Models
{
    /// <summary>
    /// Describes how a PBI was created.
    /// </summary>
    public enum PbiOrigin
    {
        /// <summary>Generated by the AI story-generation pipeline.</summary>
        AiGenerated,
        /// <summary>Created automatically by an integrated bot (e.g., Discord bot).</summary>
        BotGenerated,
        /// <summary>Created manually by a user through the web interface.</summary>
        WebUserCreated
    }
}
