using AutoFixture;
using ScrumPilot.Shared.Models;

namespace ScrumPilot.API.Services
{
    public class StudentService : IStudentService
    {

        public List<Student> GetStudents()
        {
            //Create our fixture
            var fixture = new Fixture();

            //Customize the fixture to create students with specific properties
            //In this case, we want to create students in grade 12
            //The remaining properties are automatically generated by AutoFixture
            var students = fixture
                .Build<Student>()
                .With(s => s.GradeLevel, 12)
                .CreateMany(5)
                .ToList();

            return students;
        }
    }
}
